version: "3"
services:
  app:
    container_name: containerize_app_1
    build:
      context: ./app
    ports:
      - "8000:8000" # Map port 8000 on the container to the same port on the docker network
    volumes:
      - ./app:/app  # Mount the host 'app' directory to the 'app' directory inside the container
      


  nginx:
    image: nginx
    container_name: containerize_nginx_1
    ports:
      - "80:80"
      - "443:443" # Map these ports on on the container to the same ports on the docker network
    volumes:
      - ./nginx/files/localhost.crt:/etc/nginx/certs/localhost.crt  # Mount the Cert file so it's not baked into the app
      - ./nginx/files/localhost.key:/etc/nginx/certs/localhost.key  # Mount the key file so it's not baked into the app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf           # Mount the Nginx.conf file from the sourcecode as the default.conf flime for nginx
    depends_on:
      - app  # Don't launch Nginx without an running version of the main app container (lines 3-10)
    networks:
      - default
    
networks:
  default:
    name: containerize_network
