version: "3"
services:
  app:
    container_name: containerize_app_1
    build:
      context: ./app
      args:
        options: --reload
    ports:
      - "8000:8000"


  nginx:
    image: nginx
    container_name: containerize_nginx_1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/files/localhost.crt:/etc/nginx/certs/server.crt
      - ./nginx/files/localhost.key:/etc/nginx/certs/server.key
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - containerize_app_1
    
networks:
  default:
    external:
      name: containerize_network